# Generated by Django 4.1 on 2023-01-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nr_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bf', models.CharField(max_length=32, verbose_name='播放量')),
                ('pl', models.CharField(max_length=32, verbose_name='评论量')),
                ('dz', models.CharField(max_length=32, verbose_name='点赞量')),
            ],
            options={
                'db_table': 'nr_list',
            },
        ),
        migrations.CreateModel(
            name='url_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='网站名称')),
                ('url', models.CharField(max_length=100, verbose_name='网站地址')),
            ],
            options={
                'db_table': 'url_name',
            },
        ),
    ]
